### ISSUE TITLE
Version Statutes

### ISSUE THREAD

**Issue by zmon** [codeforkansascity/cmr-clinic-admin-api#231]
- [ ] How to check for duplicates?
# ToDo
- [ ] Create table law_version_statuses to replace the constant version_status
- [ ] Add Law
- [ ] View Law
    - [ ] Pending Review List
    - [X] History of Changes
- [ ] Create Version
    - [ ] Copy Law Exceptions over
- [ ] View Version
- [ ] Edit Version
- [ ] Approve Version
- [ ] Cancel Version
- [ ] Refuse Version
